- name: get awslogs-agent setup
  get_url:
    url: "https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py"
    dest: "/home/{{ owner }}"
- name: run setup.py
  command: "sudo python ./awslogs-agent-setup.py -n --region {{ aws_region }} -c /var/log/syslog"
  args:
    chdir: "/home/{{ owner }}"
    creates: "/var/awslogs/etc/awslogs.conf"
- name: Make sure the AWS Logs config is present
  template:
    src: awslogs.conf.j2
    dest: /var/awslogs/etc/awslogs.conf
  notify: restart awslogs
