---
# tasks file for cloudwatch
- name: Update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: cloudwatch_pkgs
- name:  Install pip pkgs
  pip:
    name: "{{ item }}"
  with_items: cloudwatch_pip_pkgs
- include: monitoringscripts.yml
- include: awslogs.yml
