---
# tasks file for cloudwatch
- name: Update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: cloudwatch_pkgs
- name:  Install pip pkgs
  pip:
    name: "{{ item }}"
  with_items: cloudwatch_pip_pkgs
- name: download cloudwatch scripts
  get_url:
    url: "{{ cloudwatch_scripts }}"
    dest: "/home/{{ owner }}/cloudwatch.zip"
    mode: 0755
- name: unzip cloudwatch scripts
  unarchive:
    copy: no
    src: "/home/{{ owner }}/cloudwatch.zip"
    dest: "/home/{{ owner }}/"
- name: Loop through cron jobs
  cron:
    name: "{{ item.name }}"
    state: present
    user: "{{ owner }}"
    minute: "*/5"
    hour: "*"
    month: "*"
    weekday: "*"
    job: "{{ item.script }}"
  with_items: cloudwatch_cronjobs

- include: awslogs.yml
